<?xml version="1.0"?>
<package format="3">
  <name>mission_supervisor</name>
  <version>0.0.0</version>

  <description>Mission Supervisor</description>

  <maintainer email="brahmankarnrsa@gmail.com">Aditya Brahmankar</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>uav_interfaces</depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
